### ISSUE TITLE
undefined properties of data element for web-vitals

### ISSUE THREAD

**Issue by PH1NO** [yuhui/launchext-web-vitals#10]
I've installed the Web Vitals extension to Adobe Experience Platform via the Extensions. I've created the data elements that are preset after installing Web Vitals. When I try to use the console log for metrics, I receive "undefined" for all and when I try to grab the data element via _satellite, i get the following:

_satellite.getVar('Web-Vitals_Delta', event)
VM9:106 🚀 Failed to execute data element module web-vitals-js/src/lib/dataElements/metricDelta.js for data element Web-Vitals_Delta. Cannot read properties of undefined (reading 'webvitals')
TypeError: Cannot read properties of undefined (reading 'webvitals')

Browsers used:

- Google Chrome - Version 108.0.5359.99 (Official Build) (64-bit)
- Microsoft Edge - Version 108.0.1462.46 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/51916472/211580725-5d099ad8-60bd-4f0c-a88d-f56319c1b80a.png)

**Comment by yuhui** [comment]
@PH1NO The Data Elements have to be used in a Rule that has one of the Events from my Extension. For example, if you have a Rule that is triggered with the "Cumulative Layout Shift (CLS)" Event, then in _that_ Rule's Conditions and/or Actions, you can use the Data Elements from my Extension. Then you'll be able to get the expected values.

So my question is: in your Rule(s) where you are using these Web Vitals Data Elements, which Event(s) are you triggering with?

**Comment by PH1NO** [comment]
Hi @yuhui , thank you for your reply. So I missed the step of adding those events to the rule, I've done a separate rule on it's own to fire when any of those Web Vitals events occur and I've tried it on a page load rule. When I try to send those data elements through the actions (via set variables) or in custom code, I don't see any results. 

Here is my set up for the rule
![image](https://user-images.githubusercontent.com/51916472/211620870-66be99a1-b3c3-4d3e-8c09-77c271e87001.png)


Here is the data element set up (just selected my Attribution data element for this example)
![image](https://user-images.githubusercontent.com/51916472/211621138-8549c791-eacb-4455-97a7-d58907a413d4.png)


Here is the error I get for the Attribution one:
![image](https://user-images.githubusercontent.com/51916472/211621258-61acdacd-aae9-4165-b69b-562d2474f6c5.png)


When i tried console logging it, that threw an error as well stating that the web-vitals cannot grab any data due to it being undefined.

Unless I'm implementing incorrectly? But I tried going through the step by step process I've seen with your extension.

Thanks so much for your assistance

**Comment by yuhui** [comment]
Hi @PH1NO, can you provide the URL of the web page where you’re using my Web Vitals extension? Or if you’re not able to do that, can you provide the URL of your assets.adobedtm.com Launch environment script?

You can email me at yuhui (at) yuhui (dot) sg.

**Comment by PH1NO** [comment]
Will do. Thank you!

**Comment by PH1NO** [comment]
Thank you @yuhui for your assistance!
