### ISSUE TITLE
Web Clicks Lowered Down In terms of Recording in Adobe Analytics Database

### ISSUE THREAD

**Issue by jysharmasilabs** [yuhui/launchext-web-vitals#12]
**Web Clicks Lowered Down**
After the integration of Web Vitals, we are observing Web Clicks Lowered Down to 52% In terms of Recording in Adobe Analytics Database. These lowered numbers in the web click records we have observed are from Google(Chrome) Browser. 

When we did a deeper analysis then we found that this decrease in web clicks in the analytics record is lowered from the natural search channel which is the search engine. And, we also found it as google chrome whose users' clicks got lowered down. This happened right after integration on October 24. The moment we disabled it from the website we started to see an increase in the number of clicks 

**To Reproduce: You can check our main website www.silabs.com**
we have disabled we vitals configurations from Adobe Launch for our testing purpose and we are seeing numbers getting back to what they are. This means web clicks are trending up. So can't give you an example to reproduce

**Expected behavior**
We don't expect web clicks to get affected by any extension integrated. we are not sure about the js code or APIs run at the back for web vitals integration

**Screenshots**
This is the first dip that happened right after the integration 
![image](https://user-images.githubusercontent.com/113210969/221930506-f0e75280-ca5e-487a-8d9b-57c0cfe3018a.png)

After October web clicks lowered 
![image](https://user-images.githubusercontent.com/113210969/221930864-bd3476a9-8e03-4c14-babe-52e2f222448c.png)

After disabling configurations: web clicks started trending up in the system.
![image](https://user-images.githubusercontent.com/113210969/221931057-f173063a-b929-4c65-b5fb-72c1849a0f6d.png)

We want your help in understanding why this happening?

**Comment by yuhui** [comment]
@jysharmasilabs I wouldn’t expect my extension to interfere with your web clicks tracking. Let me check your website with your current Launch library. Which rule in your Launch library should I look for that tracks your web clicks?

**Comment by jysharmasilabs** [comment]
@yuhui Web Clicks in Adobe Analytics are measured by Activity Map Application items like Activity Map Page, Activity Map Link, and Activity Map Region. We don't have any separate custom events or evar that measure these.

**Comment by yuhui** [comment]
@jysharmasilabs, oh yes, I see this now in your screenshots, I missed that out when reading your issue earlier.

Can you do me a favour? Please build a library in your Development environment where you include my Web Vitals extension and any rules and data elements that you’ve configured with it. Then send me the script URL for that development library. I can then use that to test with your website. Thanks for your assistance.

**Comment by jysharmasilabs** [comment]
Hey Yuhui,

Apologies for the late response. I have pushed the web vitals configuration to our dev environment http://wwwdev.silabs.com/ you could see CLS/LCP/FID firing on pages. Please let me know how I can help you more in resolving the issue. Please let me know what you expect from my end to check.

Just for your reference when I enabled the launch extension then I saw the below settings in the extension as default. Hope they are okay. 

![image](https://user-images.githubusercontent.com/113210969/232905117-d48c5e82-6f2e-4d27-9727-54d16e329923.png)

**Comment by yuhui** [comment]
@jysharmasilabs , I'm not able to open http://wwwdev.silabs.com/. I assume it's behind a firewall.

Can you send the <script> link of your Launch property's Development environment? I'll load that <script> in my browser to test with your production site, https://www.silabs.com/

**Comment by jysharmasilabs** [comment]
@yuhui Our dev environment is under a firewall and you can not, unfortunately, access it without our private network. But I have pushed my webvitals configuration to stage https://wwwqa.silabs.com so you can test in this environment. I might have to remove it after 24 hrs due to other deployments so if possible can you pls test it out within 24 hours and share with me what is the issue?

**Comment by yuhui** [comment]
@jysharmasilabs, thanks, noted on this. Let me try to troubleshoot this now.

**Comment by yuhui** [comment]
@jysharmasilabs, I've tested your website a few times and could not find any cases where Activity Map clicks were _not_ clicked.

I've attached this file here showing the hits that had been recorded in Adobe Experience Platform Debugger.
[Adobe Experience Platform Debugger - Thursday, April 27th 2023, 11_09_21 pm.xlsx](https://github.com/yuhui/launchext-web-vitals/files/11345255/Adobe.Experience.Platform.Debugger.-.Thursday.April.27th.2023.11_09_21.pm.xlsx)

Columns B-E: Homepage page view and Web Vitals hits.
Then, I clicked the header menu: Products > Bluetooth.
Column F: Header menu click. You can see the **Activity Map data** at cells F24-F26 and F32-F34.
Columns G-H: Bluetooth page view and Web Vitals hits.
Then, I clicked the "Learn more about security" button.
Columns I-J: Security page view and Web Vitals hits.
Then, I clicked the "Contact us" right side tab.
Column K: "Contact us" tab click.
I closed the "Contact us" overlay. Then, I clicked the header logo.
Column L: Header logo click. You can see the **Activity Map data** at cells L24-L26 and L32-L34.
Columns M-N: Homepage page view and Web Vitals hits.

This is probably not the response that you were expecting, but as far as I can tell, I don't see Activity Map data collection being affected by Web Vitals measurement. However, given that you _are_ seeing this impact, I'd like to suggest that you implement Web Vitals natively, i.e. remove my extension and ask your developers to add the necessary code. Then see if you still get the same impact in your Activity Map data.
