### ISSUE TITLE
Web Vitals Not Working

### ISSUE THREAD

**Issue by jysharmasilabs** [yuhui/launchext-web-vitals#6]
**Web Vitals Not Working**
I have integrated Web Vitals with Adobe Launch. Launch Rules for LCP, FID, & CLS are configured. However when I tested it out at its throwing an Error in the developer console. 

**To Reproduce**
1. Go to 'https://wwwqa.silabs.com/'
2. Click the 'Console tab of the developer inspect window'
3. Scroll down to 'where Web Vitals loaded successfully'
4. See error "Uncaught (in promise) ReferenceError: webVitals is not defined
    at launch-1fcf4720ea67-staging.min.js:formatted:12954:29"

**Expected behavior**
There should not be any errors. Adobe Launch rules for CLS, FID, & LCP should have triggered.

**Screenshots**
<img width="539" alt="image" src="https://user-images.githubusercontent.com/113210969/189438980-0993a0a6-46b2-49d3-b45e-8a1be2bcda6c.png">

<img width="954" alt="image" src="https://user-images.githubusercontent.com/113210969/189439140-93efc05b-7402-411c-aac6-068a1dad5b84.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [Version 105.0.5195.52 (Official Build) (x86_64)]

**Additional context**
The error looks like a bug in the web vitals extension

**Comment by yuhui** [comment]
@jysharmasilabs Thanks for opening this issue. It looks like the WebVitals JS library has been moved to a different path. I'll update the extension to reference that new path. Please look out for an updated version of the extension in your Tags extension library.

Thanks again for your detailed issue! 😄

**Comment by jysharmasilabs** [comment]
Hi Yuhui,

Any update on updated version?

Thanks,
Jyoti

From: Yuhui ***@***.***>
Date: Tuesday, September 13, 2022 at 11:14 PM
To: yuhui/launchext-web-vitals ***@***.***>
Cc: Jyoti Sharma ***@***.***>, Mention ***@***.***>
Subject: Re: [yuhui/launchext-web-vitals] Web Vitals Not Working (Issue #6)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@jysharmasilabs<https://urldefense.com/v3/__https:/github.com/jysharmasilabs__;!!N30Cs7Jr!TkQ10B1whnW0KLj_sTFAdKZS7lWEBFq7x9_93sTeqSlm4ud2kwmVy7RnT1cZtsQ9lSQn9XZDf3wtYJhKNVErv015sRU$> Thanks for opening this issue. It looks like the WebVitals JS library has been moved to a different path. I'll update the extension to reference that new path. Please look out for an updated version of the extension in your Tags extension library.

Thanks again for your detailed issue! 😄

**Comment by yuhui** [comment]
@jysharmasilabs apologies for the late response. Yes, this has been fixed in v1.2.0 of the extension, which is available in the Tags extensions catalogue now.

**Comment by jysharmasilabs** [comment]
Thanks Yuhui for the update. I wanted to check in with you that is it necessary to send separate beacon for LCP/FID/CLS? This is something documentation says. As we are already sending beacon for every DOM Ready page loads so  want to avoid extra server hits. I am facing trouble in the configuration of Web Vitals. Adobe server Hit is not happening if I am not passing Send Beacon actions in separate rules for LCP/FDI/CLS. Below is screenshot for CLS rule and similarly FDI and LCP are existing right now.
***@***.***

However, If will add SEND Beacon actions to them then hit starts happening. But for us that is separate server calls which we want to avoid.
***@***.***

If possible can we schedule a time next week? We are Austin, TX and CDT time zone. Let me know if you can do it anytime next week. Then I can send you zoom invite.

Looking for the response.

Thanks

From: Yuhui ***@***.***>
Date: Friday, September 30, 2022 at 8:39 AM
To: yuhui/launchext-web-vitals ***@***.***>
Cc: Jyoti Sharma ***@***.***>, Mention ***@***.***>
Subject: Re: [yuhui/launchext-web-vitals] Web Vitals Not Working (Issue #6)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@jysharmasilabs<https://urldefense.com/v3/__https:/github.com/jysharmasilabs__;!!N30Cs7Jr!QiPU_a2nIbAu0d_ereyS9KT38IztX1WNMOe8xK0VYNZMK_2-45C4xz89POnYjVtJghIU9ZTZTD3oft8AeHu3NFmlgSg$> apologies for the late response. Yes, this has been fixed in v1.2.0 of the extension, which is available in the extensions catalogue now.

**Comment by yuhui** [comment]
@jysharmasilabs my extension doesn't allow for batching up of Web Vitals measurements.

Practically, it also doesn't make sense, because each Web Vitals measurement occurs when the browser has performed that measurement. For example, TTFB will be measured when the first byte is received, LCP will be measured when there is a repaint (re-render) of the content, etc.

If volume of server calls is your concern, then you can consider measuring only the Web Vitals metrics that you consider to be the most important to your business.
